# Generated by Django 3.1 on 2020-08-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='data',
            new_name='date',
        ),
    ]
